### PR TITLE
style(datagrid): bring the theme slot switch and the grid coordinator back under the lint limits

### PR DESCRIPTION
**Pull request by datlechin**
`swiftlint lint --strict` fails on `main` with two errors from #2781:

```
TablePro/Theme/ThemeDefinition.swift:212:1: error: Vertical Whitespace before Closing Braces
TablePro/Views/Results/DataGridCoordinator.swift:32:7: error: Type Body Length: Class body should
    span 1100 lines or less excluding comments and whitespace: currently spans 1101 lines
```

PR CI never runs that. The `lint` job lives in `build.yml`, which only fires on a `v*` tag, so this is
waiting at the next release rather than on any pull request.

The blank line goes. For the coordinator, `visualState(for:)` moves next to `visualState(of:atDisplayRow:)`,
which already lives in `DataGridView+RowIdentity.swift`: the two are the same question asked with and
without a resolved row, so the pair belongs together and the class drops back under the limit without a
line being invented or deleted.

`swiftlint lint --strict` is clean and the app builds.

### CODE REVIEW

**Comment by datlechin** [comment]
Obsolete. Both violations came from #2781, which #2790 reverted out of `main`, and `swiftlint lint --strict` is clean there now. If the theme engine work returns, the `ThemeDefinition.swift` blank line and `DataGridCoordinator`'s 1101-line body come back with it; the fix is the one in this branch's diff.
